RapidApiConsume/Models/SearchLocationViewModel.cs
namespace RapidApiConsume.Models
{
    public class SearchLocationViewModel
    {
        public string dest_id { get; set; }
    }
}

RapidApiConsume/Controllers/SearchLocationController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RapidApiConsume.Models;

namespace RapidApiConsume.Controllers
{
    public class SearchLocationController : Controller
    {
        public async Task<IActionResult> Index(string city)
        {
            if (!string.IsNullOrEmpty(city))
            {
                var client = new HttpClient();
                var request = new HttpRequestMessage
                {
                    Method = HttpMethod.Get,
                    RequestUri = new Uri($"https://booking-com.p.rapidapi.com/v1/hotels/locations?name={city}&locale=en-gb"),
                    Headers =
    {
        { "X-RapidAPI-Key", "e377acc97emsh8b49d7ff2f70369p1d60f2jsn2c2b95aa1ebb" },
        { "X-RapidAPI-Host", "booking-com.p.rapidapi.com" },
    },
                };
                using (var response = await client.SendAsync(request))
                {
                    response.EnsureSuccessStatusCode();
                    var body = await response.Content.ReadAsStringAsync();
                    var values = JsonConvert.DeserializeObject<List<SearchLocationViewModel>>(body);
                    return View(values.ToList());
                }
            
            }
            else
            {
                var client = new HttpClient();
                var request = new HttpRequestMessage
                {
                    Method = HttpMethod.Get,
                    RequestUri = new Uri($"https://booking-com.p.rapidapi.com/v1/hotels/locations?name=istanbul&locale=en-gb"),
                    Headers =
    {
        { "X-RapidAPI-Key", "e377acc97emsh8b49d7ff2f70369p1d60f2jsn2c2b95aa1ebb" },
        { "X-RapidAPI-Host", "booking-com.p.rapidapi.com" },
    },
                };
                using (var response = await client.SendAsync(request))
                {
                    response.EnsureSuccessStatusCode();
                    var body = await response.Content.ReadAsStringAsync();
                    var values = JsonConvert.DeserializeObject<List<SearchLocationViewModel>>(body);
                    return View(values.ToList());
                }
            }
         
        }
    }
}

RapidApiConsume/Views/SearchLocation/Index.cshtml
@model List<SearchLocationViewModel>
@{
    Layout = null;
}
<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
<div class="container">
    <br />
    <br />
    @using (Html.BeginForm("Index", "SearchLocation", FormMethod.Post))
    {
        <label>Şehir Adını Giriniz</label>
        <input type="text" class="form-control" name="city"/>
        <br />
        <button class="btn btn-dark">Şehir Destinasyon ID getir</button>
    }
    <hr />
    <table class="table table-hover">
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.dest_id</td>
            </tr>
        }
    </table>
</div>